"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
from decouple import config
import dj_database_url
from django.core.exceptions import ImproperlyConfigured


from django.core.management.utils import get_random_secret_key
"""
print(f"SECRET_KEY: {get_random_secret_key()}") 
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent
TEMPLATES_DIR = BASE_DIR / 'templates'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'DJANGO_SECRET_KEY', 
    cast=str, 
    default=get_random_secret_key()
)

# This will print a new random secret key each time the server starts, which is not ideal for production. 
# Make sure to set a fixed secret key in your .env file for production use.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config(
    'DJANGO_DEBUG', 
    cast=bool, 
    default=False
)

SERVE_MEDIA = config(
    'DJANGO_SERVE_MEDIA',
    cast=bool,
    default=DEBUG,
)

SERVE_STATIC = config(
    'DJANGO_SERVE_STATIC',
    cast=bool,
    default=DEBUG,
)

ALLOWED_HOSTS = [
    ".vercel.app",
    "django-deploy-app-b6mm7.ondigitalocean.app",
    "www.django-deploy-app-b6mm7.ondigitalocean.app",
    "project.kdadesign.tech",
    "www.project.kdadesign.tech",
    "127.0.0.1",
    "localhost",
]

env_allowed_hosts = config(
    'DJANGO_ALLOWED_HOSTS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

ALLOWED_HOSTS += [
    host for host in env_allowed_hosts
    if not host.startswith(('http://', 'https://')) and '/' not in host
]

vercel_url = config('VERCEL_URL', default='', cast=str).strip()
if vercel_url:
    ALLOWED_HOSTS.append(vercel_url)

if DEBUG:
    ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Cross Site Request Forgery (CSRF) Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://*.django-deploy-app-b6mm7.ondigitalocean.app',
    'https://*.vercel.app',
]

env_csrf_trusted_origins = config(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [s.strip().rstrip('/') for s in v.split(',') if s.strip()],
)

CSRF_TRUSTED_ORIGINS += [
    origin for origin in env_csrf_trusted_origins
    if origin.startswith(('http://', 'https://'))
]

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

SECURE_HSTS_SECONDS = config(
    'SECURE_HSTS_SECONDS',
    cast=int,
    default=31536000 if not DEBUG else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    cast=bool,
    default=not DEBUG,
)
SECURE_HSTS_PRELOAD = config(
    'SECURE_HSTS_PRELOAD',
    cast=bool,
    default=not DEBUG,
)
SECURE_SSL_REDIRECT = config(
    'SECURE_SSL_REDIRECT',
    cast=bool,
    default=not DEBUG,
)
SESSION_COOKIE_SECURE = config(
    'SESSION_COOKIE_SECURE',
    cast=bool,
    default=not DEBUG,
)
CSRF_COOKIE_SECURE = config(
    'CSRF_COOKIE_SECURE',
    cast=bool,
    default=not DEBUG,
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURE_HSTS_SECONDS = config(
#     'SECURE_HSTS_SECONDS',
#     cast=int,
#     default=31536000 if not DEBUG else 0,
# )
# SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
#     'SECURE_HSTS_INCLUDE_SUBDOMAINS',
#     cast=bool,
#     default=not DEBUG,
# )
# SECURE_HSTS_PRELOAD = config(
#     'SECURE_HSTS_PRELOAD',
#     cast=bool,
#     default=not DEBUG,
# )
# SECURE_SSL_REDIRECT = config(
#     'SECURE_SSL_REDIRECT',
#     cast=bool,
#     default=not DEBUG,
# )
# SESSION_COOKIE_SECURE = config(
#     'SESSION_COOKIE_SECURE',
#     cast=bool,
#     default=not DEBUG,
# )
# CSRF_COOKIE_SECURE = config(
#     'CSRF_COOKIE_SECURE',
#     cast=bool,
#     default=not DEBUG,
# )

# Application definition

# Application definition
DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # add apps which you install using pip
]

LOCAL_APPS = [
    # add local apps which you create using startapp
    'apps.deploy',
    'apps.accounts',
]

# Applications definition
INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # BASE_DIR / 'templates',
            TEMPLATES_DIR
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='', cast=str).strip()
ALLOW_SQLITE_FALLBACK = config(
    'ALLOW_SQLITE_FALLBACK',
    cast=bool,
    default=DEBUG,
)

SQLITE_FALLBACK_PATH = config(
    'SQLITE_PATH',
    default='/tmp/db.sqlite3' if not DEBUG else str(BASE_DIR / 'db.sqlite3'),
    cast=str,
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_FALLBACK_PATH,
    }
}

POSTGRES_DB = config(
    "POSTGRES_DB", 
    default="", 
    cast=str
)
POSTGRES_PASSWORD = config(
   "POSTGRES_PASSWORD", 
    default="", 
    cast=str
)
POSTGRES_USER = config(
   "POSTGRES_USER", 
    default="", 
    cast=str
)
POSTGRES_HOST = config(
    "POSTGRES_HOST", 
    default="", 
    cast=str
)
POSTGRES_PORT = config(
    "POSTGRES_PORT", 
    default="", 
    cast=str
)

POSTGRES_READY = all([
    POSTGRES_DB.strip(),
    POSTGRES_PASSWORD.strip(),
    POSTGRES_USER.strip(),
    POSTGRES_HOST.strip(),
    POSTGRES_PORT.strip(),
])

if POSTGRES_READY:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
        }
    }

if DATABASE_URL and '<' not in DATABASE_URL and '>' not in DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }

if not DEBUG:
    db_engine = DATABASES['default'].get('ENGINE', '')
    if db_engine == 'django.db.backends.sqlite3' and not ALLOW_SQLITE_FALLBACK:
        raise ImproperlyConfigured(
            'Production database is not configured. Set DATABASE_URL (preferred) '
            'or POSTGRES_* variables, or set ALLOW_SQLITE_FALLBACK=1 to allow '
            'ephemeral SQLite usage.'
        )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATIC_ROOT.mkdir(exist_ok=True, parents=True)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_ROOT.mkdir(exist_ok=True, parents=True)

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'deploy:home'
LOGOUT_REDIRECT_URL = 'deploy:home'